name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build binaries
        run: bun run build:all

      - name: Calculate checksums
        working-directory: cli/bin
        run: |
          sha256sum ccf-macos-arm64 > ccf-macos-arm64.sha256
          sha256sum ccf-macos-x64 > ccf-macos-x64.sha256
          sha256sum ccf-linux-x64 > ccf-linux-x64.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cli/bin/ccf-macos-arm64
            cli/bin/ccf-macos-arm64.sha256
            cli/bin/ccf-macos-x64
            cli/bin/ccf-macos-x64.sha256
            cli/bin/ccf-linux-x64
            cli/bin/ccf-linux-x64.sha256
          draft: false
          prerelease: false
